---
# Create a Requested Flavor
- name: Create Flavor
  os_nova_flavor:
    cloud: ospcloud
    state: present
    name: "{{flavor_name}}"
    ram: "{{ram}}"
    vcpus: "{{vcpu}}"
    disk: "{{disk}}"

- name: Generate SSH Keypair
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa

- name: Create KeyPair on OpenStack
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
